apiVersion: v1
kind: Service
metadata:
  namespace: mysql-test
  name: mysql-test
  labels:
    app: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    nodePort: 31740
  selector:
    app: mysql
