apiVersion: v1
kind: Service
metadata:
  namespace: mysql-repl
  name: mysql-master
  labels:
    app: mysql-master
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 31706
  selector:
    app: mysql-master
